name: Lint and Format

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12.0
    - name: Install Flake8 and Black
      run: |
        pip install flake8 black
    - name: Run Flake8
      run: |
        flake8 .
    - name: Check formatting with Black
      run: |
        black --check .